name: CI

on:
  pull_request:
  push:
    branches: main
    tags:
    - 'v*'

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
    name: Check Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: pip install .[test]

    - name: Test regular package
      run: pytest

    - name: Uninstall package
      run: pip uninstall -y scikit-hep-testdata

    - name: Install package
      run: pip install -e .[test]

    - name: Requirements list
      run: python -m pip list

    - name: Test package
      run: python -m pytest ./tests --cov=src/skhep_testdata --cov-report=xml

    - name: Test coverage with Codecov
      if: matrix.python-version != 3.7
      uses: codecov/codecov-action@v3

  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build wheel and SDist
      run: pipx run build

    - name: Show sizes
      run: ls -lh dist

    - uses: actions/upload-artifact@v1
      with:
        name: DistPackage
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
