name: CI

on:
  pull_request:
  push:
    branches: master
    tags:
    - 'v*'

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 2.7
        - 3.5
        - 3.7
        - 3.9
    name: Check Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install -e .[test]

    - name: Requirements check
      run: python -m pip list

    - name: Test package
      run: python -m pytest


  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

      # There's no reason to produce an sdist, and it's already big
      # - name: Build sdist
      #   run: python setup.py sdist

    - name: Build wheel
      run: pipx run build --wheel

    - uses: actions/upload-artifact@v1
      with:
        name: DistPackage
        path: dist

    - uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
